using Addressbook;
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
Console.WriteLine("Welcome to Address Book Program in Address Book Main class on Master Branch");
Console.WriteLine("Enter the details to create a contact");
addressBook obj = new addressBook();
obj.create();
obj.create();
obj.display();
Console.WriteLine("Enter the first name of the contact you want to edit the details of");
string Firstname = Console.ReadLine();
Console.WriteLine("Enter the second name of the contact you want to edit the details of");
string s_name = Console.ReadLine();
obj.delete(Firstname, s_name);
obj.display();